<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5853b9b1b71fd',
	'title' => 'Globalt',
	'fields' => array (
		array (
			'key' => 'field_5853ba0581343',
			'label' => 'Sidhuvud',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5853ba1581344',
			'label' => 'Logga',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => 'Lägg till loggan',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5853ba3a81345',
			'label' => 'Sidfot',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5874a8044ce3d',
			'label' => 'Socialt',
			'name' => 'socialt',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till social länk',
			'sub_fields' => array (
				array (
					'key' => 'field_5874a8044ce3e',
					'label' => 'Tjänst',
					'name' => 'service',
					'type' => 'select',
					'instructions' => 'Välj vilka sociala tjänster du vill visa',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'instagram' => 'Instagram',
						'twitter' => 'Twitter',
						'linkedin' => 'LinkedIn',
						'youtube' => 'Youtube',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5874a8044ce3f',
					'label' => 'Länk',
					'name' => 'link',
					'type' => 'text',
					'instructions' => 'Skriv in länken till respektive tjänst.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'http://www.',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_5853bc2c81349',
			'label' => 'Kort info',
			'name' => 'info',
			'type' => 'text',
			'instructions' => 'Skriv in kort info som ni vill visa',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5873caf4a5285',
	'title' => 'Guider',
	'fields' => array (
		array (
			'key' => 'field_5874b3990ec8c',
			'label' => 'Bild',
			'name' => 'img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5874af13ebbfa',
			'label' => 'Arbetat',
			'name' => 'work',
			'type' => 'text',
			'instructions' => 'Skriv in hur länge personen har arbetat som guide. T.ex. 2002-2006',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5874b144ebbfc',
			'label' => 'Språk',
			'name' => 'language',
			'type' => 'text',
			'instructions' => 'Skriv in vilka språk guiden behärskar.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5874b15cebbfd',
			'label' => 'Favoritaktivitet',
			'name' => 'favorit',
			'type' => 'text',
			'instructions' => 'Skriv in vilken aktivitet som guiden gillar mest.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5874b125ebbfb',
			'label' => 'Tips från guiden',
			'name' => 'tips',
			'type' => 'textarea',
			'instructions' => 'Skriv in ett valfritt tips',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'guide',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5853c2df304ae',
	'title' => 'Sektioner',
	'fields' => array (
		array (
			'key' => 'field_5853c2e5d7102',
			'label' => 'Sektioner',
			'name' => 'sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Lägg till en sektion',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '5853c2f0626ab',
					'name' => 'hero',
					'label' => 'Hero',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5853c30cd7103',
							'label' => 'Bild',
							'name' => 'img',
							'type' => 'image',
							'instructions' => 'Lägg till bilden du vill ha',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5853c3a0d7107',
							'label' => 'Vill du ha med text?',
							'name' => 'hero.text',
							'type' => 'true_false',
							'instructions' => 'Om du vill ha med text, kryssa i rutan.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_5853c339d7104',
							'label' => 'Text - rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'Skriv in en rubrik',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5853c3a0d7107',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5853c35dd7105',
							'label' => 'Text - innehåll',
							'name' => 'text',
							'type' => 'text',
							'instructions' => 'Skriv in kort text. Ligger under rubriken.',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5853c3a0d7107',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5853c38dd7106',
					'name' => 'two',
					'label' => 'Två kolumner',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5875441995eb9',
							'label' => 'Vill du ha två bilder?',
							'name' => 'images',
							'type' => 'true_false',
							'instructions' => 'Klicka i om du vill ha två bilder istället.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_5875446d65866',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5875441995eb9',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5853e798c4bf1',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => 'Skriv in texten som du vill ha',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5875441995eb9',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_5853e829c4bf3',
							'label' => 'Bild',
							'name' => 'img',
							'type' => 'image',
							'instructions' => 'Välj bild',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5875444095eba',
							'label' => 'Bild',
							'name' => 'img_1',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5875441995eb9',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5873850743138',
					'name' => 'columns',
					'label' => 'Kolumner',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5873852043139',
							'label' => 'Rubrik',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5873852b4313a',
							'label' => 'Format',
							'name' => 'format',
							'type' => 'select',
							'instructions' => 'Välj hur många kolumner per rad som ska visas.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								12 => 'En',
								6 => 'Två',
								4 => 'Tre',
								3 => 'Fyra',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5873857d4313b',
							'label' => 'Kolumner',
							'name' => 'column',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Lägg till rad',
							'sub_fields' => array (
								array (
									'key' => 'field_587385b34313c',
									'label' => 'Bild',
									'name' => 'img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_587385ca4313d',
									'label' => 'Rubrik',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_5873852b4313a',
												'operator' => '!=',
												'value' => '12',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_587385d54313e',
									'label' => 'Text',
									'name' => 'text',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => 'wpautop',
								),
								array (
									'key' => 'field_5873869f43143',
									'label' => 'Ska det finnas en knapp?',
									'name' => 'button',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
								),
								array (
									'key' => 'field_5873862743140',
									'label' => 'Knapplänk',
									'name' => 'button_link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_5873869f43143',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
										0 => 'page',
										1 => 'guide',
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'allow_archives' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_5873864643141',
									'label' => 'Knapptext',
									'name' => 'button_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_5873869f43143',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5874e076641b8',
					'name' => 'testimonial',
					'label' => 'Testimonial',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5874e07e641b9',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'text',
							'instructions' => 'Skriv in en kort text om du vill.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5874e09e641ba',
							'label' => 'Bakgrundsfärg',
							'name' => 'color',
							'type' => 'select',
							'instructions' => 'Välj vilken bakgrundsfärg den sa ha.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'lightgreen' => 'Ljusgrön',
								'green' => 'Grön',
								'lightgrey' => 'Ljusgrå',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
